*Bézout's identity:* For $a eq.not 0$, $b eq.not 0$, $d = gcd(a,b)$ is the smallest positive integer with integer solutions to $a x + b y = d$. All solutions:
$ (x + (k b) / gcd(a,b), quad y - (k a) / gcd(a,b)), quad k in ZZ $

*Pythagorean triples:* Uniquely generated by:
$ a = k(m^2 - n^2), quad b = k(2m n), quad c = k(m^2 + n^2) $
with $m > n > 0$, $k > 0$, $gcd(m, n) = 1$, and $m, n$ not both odd.

*Möbius function:*
$ mu(n) = cases(0 & "if" n "is not squarefree", 1 & "if" n "has even number of prime factors", -1 & "if" n "has odd number of prime factors") $

*Möbius inversion:*
$ g(n) = sum_(d | n) f(d) arrow.l.r f(n) = sum_(d | n) mu(d) g(n \/ d) $
$ sum_(d | n) mu(d) = [n = 1] quad "(very useful)" $
$ g(n) = sum_(n | d) f(d) arrow.l.r f(n) = sum_(n | d) mu(d \/ n) g(d) $
$ g(n) = sum_(1 lt.eq m lt.eq n) f(floor(n / m)) arrow.l.r f(n) = sum_(1 lt.eq m lt.eq n) mu(m) g(floor(n / m)) $

*Reference primes:* 970592641 (31-bit), 31443539979727 (45-bit), 3006703054056749 (52-bit). $p = 962592769$: $2^21 | p-1$. There are 78498 primes below $10^6$.

Primitive roots exist mod any prime power $p^a$, except $p = 2, a > 2$.

*Estimates:* $sum_(d | n) d = O(n log log n)$.

\#divisors of $n$: ~100 for $n < 5 dot 10^4$, ~500 for $n < 10^7$, ~2000 for $n < 10^10$, ~200000 for $n < 10^19$.
