name: check-tracker

on:
  push:
    branches: [ "*" ]
  pull_request: 
    branches: [ "*" ]

jobs:
  check-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run check-tracker
        run: |
          python scripts/check-tracker.py tracker.yaml content
